/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWritingRouteImport } from './routes/_authenticated/writing'
import { Route as AuthenticatedWeaknessRouteImport } from './routes/_authenticated/weakness'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedQuizBankRouteImport } from './routes/_authenticated/quiz-bank'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedErrorBookRouteImport } from './routes/_authenticated/error-book'
import { Route as AuthenticatedDataTransferRouteImport } from './routes/_authenticated/data-transfer'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn/index'
import { Route as AuthenticatedWritingTipsRouteImport } from './routes/_authenticated/writing/tips'
import { Route as AuthenticatedWritingTemplatesRouteImport } from './routes/_authenticated/writing/templates'
import { Route as AuthenticatedWritingSamplesRouteImport } from './routes/_authenticated/writing/samples'
import { Route as AuthenticatedSettingsAiCostRouteImport } from './routes/_authenticated/settings/ai-cost'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedExamHistoryRouteImport } from './routes/_authenticated/exam/history'
import { Route as AuthenticatedExamEssayRouteImport } from './routes/_authenticated/exam/essay'
import { Route as AuthenticatedExamCompRouteImport } from './routes/_authenticated/exam/comp'
import { Route as AuthenticatedExamCaseRouteImport } from './routes/_authenticated/exam/case'
import { Route as AuthenticatedLearnChapterIdIndexRouteImport } from './routes/_authenticated/learn/$chapterId/index'
import { Route as AuthenticatedQaChapterIdKpIdRouteImport } from './routes/_authenticated/qa/$chapterId/$kpId'
import { Route as AuthenticatedLearnChapterIdKpIdQaRouteImport } from './routes/_authenticated/learn/$chapterId/$kpId/qa'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWritingRoute = AuthenticatedWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeaknessRoute = AuthenticatedWeaknessRouteImport.update({
  id: '/weakness',
  path: '/weakness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizBankRoute = AuthenticatedQuizBankRouteImport.update({
  id: '/quiz-bank',
  path: '/quiz-bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorBookRoute = AuthenticatedErrorBookRouteImport.update({
  id: '/error-book',
  path: '/error-book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataTransferRoute =
  AuthenticatedDataTransferRouteImport.update({
    id: '/data-transfer',
    path: '/data-transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedWritingTipsRoute =
  AuthenticatedWritingTipsRouteImport.update({
    id: '/tips',
    path: '/tips',
    getParentRoute: () => AuthenticatedWritingRoute,
  } as any)
const AuthenticatedWritingTemplatesRoute =
  AuthenticatedWritingTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedWritingRoute,
  } as any)
const AuthenticatedWritingSamplesRoute =
  AuthenticatedWritingSamplesRouteImport.update({
    id: '/samples',
    path: '/samples',
    getParentRoute: () => AuthenticatedWritingRoute,
  } as any)
const AuthenticatedSettingsAiCostRoute =
  AuthenticatedSettingsAiCostRouteImport.update({
    id: '/settings/ai-cost',
    path: '/settings/ai-cost',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamHistoryRoute =
  AuthenticatedExamHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedExamRoute,
  } as any)
const AuthenticatedExamEssayRoute = AuthenticatedExamEssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => AuthenticatedExamRoute,
} as any)
const AuthenticatedExamCompRoute = AuthenticatedExamCompRouteImport.update({
  id: '/comp',
  path: '/comp',
  getParentRoute: () => AuthenticatedExamRoute,
} as any)
const AuthenticatedExamCaseRoute = AuthenticatedExamCaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => AuthenticatedExamRoute,
} as any)
const AuthenticatedLearnChapterIdIndexRoute =
  AuthenticatedLearnChapterIdIndexRouteImport.update({
    id: '/$chapterId/',
    path: '/$chapterId/',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)
const AuthenticatedQaChapterIdKpIdRoute =
  AuthenticatedQaChapterIdKpIdRouteImport.update({
    id: '/$chapterId/$kpId',
    path: '/$chapterId/$kpId',
    getParentRoute: () => AuthenticatedQaRoute,
  } as any)
const AuthenticatedLearnChapterIdKpIdQaRoute =
  AuthenticatedLearnChapterIdKpIdQaRouteImport.update({
    id: '/$chapterId/$kpId/qa',
    path: '/$chapterId/$kpId/qa',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/data-transfer': typeof AuthenticatedDataTransferRoute
  '/error-book': typeof AuthenticatedErrorBookRoute
  '/exam': typeof AuthenticatedExamRouteWithChildren
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/qa': typeof AuthenticatedQaRouteWithChildren
  '/quiz': typeof AuthenticatedQuizRoute
  '/quiz-bank': typeof AuthenticatedQuizBankRoute
  '/review': typeof AuthenticatedReviewRoute
  '/search': typeof AuthenticatedSearchRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/weakness': typeof AuthenticatedWeaknessRoute
  '/writing': typeof AuthenticatedWritingRouteWithChildren
  '/exam/case': typeof AuthenticatedExamCaseRoute
  '/exam/comp': typeof AuthenticatedExamCompRoute
  '/exam/essay': typeof AuthenticatedExamEssayRoute
  '/exam/history': typeof AuthenticatedExamHistoryRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/ai-cost': typeof AuthenticatedSettingsAiCostRoute
  '/writing/samples': typeof AuthenticatedWritingSamplesRoute
  '/writing/templates': typeof AuthenticatedWritingTemplatesRoute
  '/writing/tips': typeof AuthenticatedWritingTipsRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/qa/$chapterId/$kpId': typeof AuthenticatedQaChapterIdKpIdRoute
  '/learn/$chapterId/': typeof AuthenticatedLearnChapterIdIndexRoute
  '/learn/$chapterId/$kpId/qa': typeof AuthenticatedLearnChapterIdKpIdQaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/data-transfer': typeof AuthenticatedDataTransferRoute
  '/error-book': typeof AuthenticatedErrorBookRoute
  '/exam': typeof AuthenticatedExamRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/qa': typeof AuthenticatedQaRouteWithChildren
  '/quiz': typeof AuthenticatedQuizRoute
  '/quiz-bank': typeof AuthenticatedQuizBankRoute
  '/review': typeof AuthenticatedReviewRoute
  '/search': typeof AuthenticatedSearchRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/weakness': typeof AuthenticatedWeaknessRoute
  '/writing': typeof AuthenticatedWritingRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/exam/case': typeof AuthenticatedExamCaseRoute
  '/exam/comp': typeof AuthenticatedExamCompRoute
  '/exam/essay': typeof AuthenticatedExamEssayRoute
  '/exam/history': typeof AuthenticatedExamHistoryRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/ai-cost': typeof AuthenticatedSettingsAiCostRoute
  '/writing/samples': typeof AuthenticatedWritingSamplesRoute
  '/writing/templates': typeof AuthenticatedWritingTemplatesRoute
  '/writing/tips': typeof AuthenticatedWritingTipsRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/qa/$chapterId/$kpId': typeof AuthenticatedQaChapterIdKpIdRoute
  '/learn/$chapterId': typeof AuthenticatedLearnChapterIdIndexRoute
  '/learn/$chapterId/$kpId/qa': typeof AuthenticatedLearnChapterIdKpIdQaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/data-transfer': typeof AuthenticatedDataTransferRoute
  '/_authenticated/error-book': typeof AuthenticatedErrorBookRoute
  '/_authenticated/exam': typeof AuthenticatedExamRouteWithChildren
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/qa': typeof AuthenticatedQaRouteWithChildren
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/quiz-bank': typeof AuthenticatedQuizBankRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/weakness': typeof AuthenticatedWeaknessRoute
  '/_authenticated/writing': typeof AuthenticatedWritingRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/exam/case': typeof AuthenticatedExamCaseRoute
  '/_authenticated/exam/comp': typeof AuthenticatedExamCompRoute
  '/_authenticated/exam/essay': typeof AuthenticatedExamEssayRoute
  '/_authenticated/exam/history': typeof AuthenticatedExamHistoryRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/ai-cost': typeof AuthenticatedSettingsAiCostRoute
  '/_authenticated/writing/samples': typeof AuthenticatedWritingSamplesRoute
  '/_authenticated/writing/templates': typeof AuthenticatedWritingTemplatesRoute
  '/_authenticated/writing/tips': typeof AuthenticatedWritingTipsRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/qa/$chapterId/$kpId': typeof AuthenticatedQaChapterIdKpIdRoute
  '/_authenticated/learn/$chapterId/': typeof AuthenticatedLearnChapterIdIndexRoute
  '/_authenticated/learn/$chapterId/$kpId/qa': typeof AuthenticatedLearnChapterIdKpIdQaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/data-transfer'
    | '/error-book'
    | '/exam'
    | '/learn'
    | '/progress'
    | '/qa'
    | '/quiz'
    | '/quiz-bank'
    | '/review'
    | '/search'
    | '/stats'
    | '/weakness'
    | '/writing'
    | '/exam/case'
    | '/exam/comp'
    | '/exam/essay'
    | '/exam/history'
    | '/settings/ai'
    | '/settings/ai-cost'
    | '/writing/samples'
    | '/writing/templates'
    | '/writing/tips'
    | '/learn/'
    | '/qa/$chapterId/$kpId'
    | '/learn/$chapterId/'
    | '/learn/$chapterId/$kpId/qa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/data-transfer'
    | '/error-book'
    | '/exam'
    | '/progress'
    | '/qa'
    | '/quiz'
    | '/quiz-bank'
    | '/review'
    | '/search'
    | '/stats'
    | '/weakness'
    | '/writing'
    | '/'
    | '/exam/case'
    | '/exam/comp'
    | '/exam/essay'
    | '/exam/history'
    | '/settings/ai'
    | '/settings/ai-cost'
    | '/writing/samples'
    | '/writing/templates'
    | '/writing/tips'
    | '/learn'
    | '/qa/$chapterId/$kpId'
    | '/learn/$chapterId'
    | '/learn/$chapterId/$kpId/qa'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/data-transfer'
    | '/_authenticated/error-book'
    | '/_authenticated/exam'
    | '/_authenticated/learn'
    | '/_authenticated/progress'
    | '/_authenticated/qa'
    | '/_authenticated/quiz'
    | '/_authenticated/quiz-bank'
    | '/_authenticated/review'
    | '/_authenticated/search'
    | '/_authenticated/stats'
    | '/_authenticated/weakness'
    | '/_authenticated/writing'
    | '/_authenticated/'
    | '/_authenticated/exam/case'
    | '/_authenticated/exam/comp'
    | '/_authenticated/exam/essay'
    | '/_authenticated/exam/history'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/ai-cost'
    | '/_authenticated/writing/samples'
    | '/_authenticated/writing/templates'
    | '/_authenticated/writing/tips'
    | '/_authenticated/learn/'
    | '/_authenticated/qa/$chapterId/$kpId'
    | '/_authenticated/learn/$chapterId/'
    | '/_authenticated/learn/$chapterId/$kpId/qa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/writing': {
      id: '/_authenticated/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AuthenticatedWritingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weakness': {
      id: '/_authenticated/weakness'
      path: '/weakness'
      fullPath: '/weakness'
      preLoaderRoute: typeof AuthenticatedWeaknessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz-bank': {
      id: '/_authenticated/quiz-bank'
      path: '/quiz-bank'
      fullPath: '/quiz-bank'
      preLoaderRoute: typeof AuthenticatedQuizBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/error-book': {
      id: '/_authenticated/error-book'
      path: '/error-book'
      fullPath: '/error-book'
      preLoaderRoute: typeof AuthenticatedErrorBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-transfer': {
      id: '/_authenticated/data-transfer'
      path: '/data-transfer'
      fullPath: '/data-transfer'
      preLoaderRoute: typeof AuthenticatedDataTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/writing/tips': {
      id: '/_authenticated/writing/tips'
      path: '/tips'
      fullPath: '/writing/tips'
      preLoaderRoute: typeof AuthenticatedWritingTipsRouteImport
      parentRoute: typeof AuthenticatedWritingRoute
    }
    '/_authenticated/writing/templates': {
      id: '/_authenticated/writing/templates'
      path: '/templates'
      fullPath: '/writing/templates'
      preLoaderRoute: typeof AuthenticatedWritingTemplatesRouteImport
      parentRoute: typeof AuthenticatedWritingRoute
    }
    '/_authenticated/writing/samples': {
      id: '/_authenticated/writing/samples'
      path: '/samples'
      fullPath: '/writing/samples'
      preLoaderRoute: typeof AuthenticatedWritingSamplesRouteImport
      parentRoute: typeof AuthenticatedWritingRoute
    }
    '/_authenticated/settings/ai-cost': {
      id: '/_authenticated/settings/ai-cost'
      path: '/settings/ai-cost'
      fullPath: '/settings/ai-cost'
      preLoaderRoute: typeof AuthenticatedSettingsAiCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/history': {
      id: '/_authenticated/exam/history'
      path: '/history'
      fullPath: '/exam/history'
      preLoaderRoute: typeof AuthenticatedExamHistoryRouteImport
      parentRoute: typeof AuthenticatedExamRoute
    }
    '/_authenticated/exam/essay': {
      id: '/_authenticated/exam/essay'
      path: '/essay'
      fullPath: '/exam/essay'
      preLoaderRoute: typeof AuthenticatedExamEssayRouteImport
      parentRoute: typeof AuthenticatedExamRoute
    }
    '/_authenticated/exam/comp': {
      id: '/_authenticated/exam/comp'
      path: '/comp'
      fullPath: '/exam/comp'
      preLoaderRoute: typeof AuthenticatedExamCompRouteImport
      parentRoute: typeof AuthenticatedExamRoute
    }
    '/_authenticated/exam/case': {
      id: '/_authenticated/exam/case'
      path: '/case'
      fullPath: '/exam/case'
      preLoaderRoute: typeof AuthenticatedExamCaseRouteImport
      parentRoute: typeof AuthenticatedExamRoute
    }
    '/_authenticated/learn/$chapterId/': {
      id: '/_authenticated/learn/$chapterId/'
      path: '/$chapterId'
      fullPath: '/learn/$chapterId/'
      preLoaderRoute: typeof AuthenticatedLearnChapterIdIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/qa/$chapterId/$kpId': {
      id: '/_authenticated/qa/$chapterId/$kpId'
      path: '/$chapterId/$kpId'
      fullPath: '/qa/$chapterId/$kpId'
      preLoaderRoute: typeof AuthenticatedQaChapterIdKpIdRouteImport
      parentRoute: typeof AuthenticatedQaRoute
    }
    '/_authenticated/learn/$chapterId/$kpId/qa': {
      id: '/_authenticated/learn/$chapterId/$kpId/qa'
      path: '/$chapterId/$kpId/qa'
      fullPath: '/learn/$chapterId/$kpId/qa'
      preLoaderRoute: typeof AuthenticatedLearnChapterIdKpIdQaRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
  }
}

interface AuthenticatedExamRouteChildren {
  AuthenticatedExamCaseRoute: typeof AuthenticatedExamCaseRoute
  AuthenticatedExamCompRoute: typeof AuthenticatedExamCompRoute
  AuthenticatedExamEssayRoute: typeof AuthenticatedExamEssayRoute
  AuthenticatedExamHistoryRoute: typeof AuthenticatedExamHistoryRoute
}

const AuthenticatedExamRouteChildren: AuthenticatedExamRouteChildren = {
  AuthenticatedExamCaseRoute: AuthenticatedExamCaseRoute,
  AuthenticatedExamCompRoute: AuthenticatedExamCompRoute,
  AuthenticatedExamEssayRoute: AuthenticatedExamEssayRoute,
  AuthenticatedExamHistoryRoute: AuthenticatedExamHistoryRoute,
}

const AuthenticatedExamRouteWithChildren =
  AuthenticatedExamRoute._addFileChildren(AuthenticatedExamRouteChildren)

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedLearnChapterIdIndexRoute: typeof AuthenticatedLearnChapterIdIndexRoute
  AuthenticatedLearnChapterIdKpIdQaRoute: typeof AuthenticatedLearnChapterIdKpIdQaRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedLearnChapterIdIndexRoute: AuthenticatedLearnChapterIdIndexRoute,
  AuthenticatedLearnChapterIdKpIdQaRoute:
    AuthenticatedLearnChapterIdKpIdQaRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedQaRouteChildren {
  AuthenticatedQaChapterIdKpIdRoute: typeof AuthenticatedQaChapterIdKpIdRoute
}

const AuthenticatedQaRouteChildren: AuthenticatedQaRouteChildren = {
  AuthenticatedQaChapterIdKpIdRoute: AuthenticatedQaChapterIdKpIdRoute,
}

const AuthenticatedQaRouteWithChildren = AuthenticatedQaRoute._addFileChildren(
  AuthenticatedQaRouteChildren,
)

interface AuthenticatedWritingRouteChildren {
  AuthenticatedWritingSamplesRoute: typeof AuthenticatedWritingSamplesRoute
  AuthenticatedWritingTemplatesRoute: typeof AuthenticatedWritingTemplatesRoute
  AuthenticatedWritingTipsRoute: typeof AuthenticatedWritingTipsRoute
}

const AuthenticatedWritingRouteChildren: AuthenticatedWritingRouteChildren = {
  AuthenticatedWritingSamplesRoute: AuthenticatedWritingSamplesRoute,
  AuthenticatedWritingTemplatesRoute: AuthenticatedWritingTemplatesRoute,
  AuthenticatedWritingTipsRoute: AuthenticatedWritingTipsRoute,
}

const AuthenticatedWritingRouteWithChildren =
  AuthenticatedWritingRoute._addFileChildren(AuthenticatedWritingRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDataTransferRoute: typeof AuthenticatedDataTransferRoute
  AuthenticatedErrorBookRoute: typeof AuthenticatedErrorBookRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRouteWithChildren
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRouteWithChildren
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedQuizBankRoute: typeof AuthenticatedQuizBankRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedWeaknessRoute: typeof AuthenticatedWeaknessRoute
  AuthenticatedWritingRoute: typeof AuthenticatedWritingRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsAiCostRoute: typeof AuthenticatedSettingsAiCostRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDataTransferRoute: AuthenticatedDataTransferRoute,
  AuthenticatedErrorBookRoute: AuthenticatedErrorBookRoute,
  AuthenticatedExamRoute: AuthenticatedExamRouteWithChildren,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQaRoute: AuthenticatedQaRouteWithChildren,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedQuizBankRoute: AuthenticatedQuizBankRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedWeaknessRoute: AuthenticatedWeaknessRoute,
  AuthenticatedWritingRoute: AuthenticatedWritingRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsAiCostRoute: AuthenticatedSettingsAiCostRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
